language: node_js
node_js:
  - stable
services:
  - postgresql

before_script:
  - psql -c 'create database freementor;' -U postgres

branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
  - npm run coveralls

